### ISSUE TITLE
configure: error: cannot find minizip/unzip.h, bailing out

### ISSUE THREAD

**Issue by eserte** [shawnlaffan/perl-alien-freexl#2]
There are no successful builds anymore reported on CPAN Testers:
https://fast2-matrix.cpantesters.org/?dist=Alien-freexl;reports=1#sl=7,1

It fails like this:
```
...
checking minizip/unzip.h usability... no
checking minizip/unzip.h presence... no
checking for minizip/unzip.h... no
configure: error: cannot find minizip/unzip.h, bailing out
nothing was installed into destdir at /opt/perl-5.38.0/lib/site_perl/5.38.0/Alien/Build/Plugin/Core/Gather.pm line 78.
Alien::Build::Plugin::Cleanse::BuildDir> Going to delete /home/cpansand/.cpan/build/2023121920/Alien-freexl-1.05-0/_alien/build_eoJI/freexl-2.0.0
Alien::Build::Plugin::Cleanse::BuildDir> Currently in /home/cpansand/.cpan/build/2023121920/Alien-freexl-1.05-0/_alien/build_eoJI/freexl-2.0.0
Alien::Build::Plugin::Cleanse::BuildDir> Going to parent of build directory
Alien::Build::Plugin::Cleanse::BuildDir> Deleted 103 items
make: *** [Makefile:1036: _alien/mm/build] Error 2
```

**Comment by shawnlaffan** [comment]
Thanks for the report.  

Minizip seems to have been removed from recent OS versions so the freexl configure script needs to be updated.  That's an upstream problem.

However, it looks like minizip is only needed for building the docs, which are not needed for an alien.  Specifying `--disable-xmldocs` as a configure arg gets things to complete again.  

I'll cut a new release shortly.

**Comment by shawnlaffan** [comment]
Alien::freexl 1.06 has been uploaded to CPAN.  I'll close this issue if/when cpantesters looks good.

**Comment by eserte** [comment]
http://fast2-matrix.cpantesters.org/?dist=Alien-freexl%201.06 → looks good so far. The free FAILs on FreeBSD are from an ancient FreeBSD system (version 10) and IMHO may be ignored. There's also a FAIL on OpenBSD, but according to http://fast2-matrix.cpantesters.org/?dist=Alien-freexl%201.06;maxver=1 there were never PASS reports from this OS.

**Comment by shawnlaffan** [comment]
Thanks for the update.  I'll close this issue now.
